version: "3.9"

services:
  mongodb-dev:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: [ "bash", "-c", "yarn start" ]
    environment:
      - DATABASE_DEV=mongodb://mongodb-dev:27017/ecommerce
      - NODE_ENV=dev
      - JWT_SECRET=DaoxGNGbKX9fPhKg3G9LStWEsAG2C6
      - JWT_EXPIRES_IN=90d
      - JWT_COOKIE_EXPIRES_IN=90
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-dev
    restart: always
    volumes:
      - ./backend:/backend
    links:
      - mongodb-dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: [ "bash", "-c", "yarn start" ]
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - backend-dev
    restart: always
    volumes:
      - ./frontend:/frontend
