version: 2.1

jobs:
  backend-unittest:
    docker:
      - image: circleci/node:12-browsers
      - image: mongo:4.1.6-xenial
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "backend/yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            cd backend
            yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "backend/yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged

workflows:
  version: 2
  run_build:
    jobs:
      - backend-unittest
